name: WLED compile

on:
    workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
        wget $$WLEDPATH$$ -O /tmp/mm.zip
        unzip /tmp/mm.zip -d /tmp
        find /tmp -maxdepth 1 -name "WLED-*" -type d > wledfoldername
        mv `cat wledfoldername` /tmp/WLED-main
    - name: Run PlatformIO
      run: |
        cd /tmp/WLED-main
        echo '[env:custom_build]' >>platformio.ini
        echo 'extends = env:esp32dev' >>platformio.ini
        echo 'build_flags = ${env:esp32dev.build_flags} ${common.debug_flags} -D LOLIN_WIFI_FIX -D USERMOD_AUDIOREACTIVE -D USERMOD_PIRSWITCH -D USERMOD_SEVEN_SEGMENT' >>platformio.ini
        echo 'lib_deps = ' >>platformio.ini
        echo '  ${env:esp32dev.lib_deps}' >>platformio.ini
        echo '  https://github.com/blazoncek/arduinoFFT.git' >>platformio.ini
        
        pio run -e custom_build || pio run -e custom_build
      env:
        PLATFORMIO_CI_SRC: /tmp/WLED-main
    - name: Copy Files
      run: |
        cd $GITHUB_WORKSPACE
        git rm -r $GITHUB_WORKSPACE/*.bin || true
        cp /tmp/WLED-main/build_output/firmware/custom_build.bin $GITHUB_WORKSPACE/
        date -I | tr -d '\n' >$GITHUB_WORKSPACE/last_update_date.txt
    - name: Commit Files
      run: |
        cd $GITHUB_WORKSPACE
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git add $GITHUB_WORKSPACE/custom_build.bin
        git add $GITHUB_WORKSPACE/last_update_date.txt
        git commit -m "Commit Custom Build"
        git push origin main
